import { readFileSync } from "node:fs";
import { PDFDocument } from "pdf-lib";
import { pdfPointsToCm, isWithinTolerance, roundToDecimals } from "../sizing/units";

export interface PdfValidationReport {
  outputPath: string;
  pageCount: number;
  expected: { widthCm: number; heightCm: number };
  actualFirstPage: { widthPt: number; heightPt: number; widthCm: number; heightCm: number };
  dimensionsOk: boolean;
  warnings: string[];
}

const CMYK_WARNING =
  "Generated by Chromium; true CMYK/PDF-X output is not guaranteed.";

export async function validatePdf(
  outputPath: string,
  expectedWidthCm: number,
  expectedHeightCm: number,
  renderWarnings: string[],
): Promise<PdfValidationReport> {
  const warnings = [...renderWarnings, CMYK_WARNING];

  let pdfBytes: Uint8Array;
  try {
    const buffer = readFileSync(outputPath);
    pdfBytes = new Uint8Array(buffer.byteLength);
    for (let i = 0; i < buffer.byteLength; i++) {
      pdfBytes[i] = buffer[i];
    }
  } catch {
    throw new Error(`Could not read generated PDF: ${outputPath}`);
  }

  const pdfDoc = await PDFDocument.load(pdfBytes);
  const pageCount = pdfDoc.getPageCount();

  if (pageCount !== 1) {
    warnings.push(`Expected 1 page, but PDF contains ${pageCount} pages.`);
  }

  const firstPage = pdfDoc.getPage(0);
  const size = firstPage.getSize();

  const actualWidthCm = roundToDecimals(pdfPointsToCm(size.width), 3);
  const actualHeightCm = roundToDecimals(pdfPointsToCm(size.height), 3);

  const widthOk = isWithinTolerance(actualWidthCm, expectedWidthCm);
  const heightOk = isWithinTolerance(actualHeightCm, expectedHeightCm);

  if (!widthOk) {
    warnings.push(
      `Width mismatch: expected ${expectedWidthCm}cm, got ${actualWidthCm}cm (${size.width}pt).`,
    );
  }
  if (!heightOk) {
    warnings.push(
      `Height mismatch: expected ${expectedHeightCm}cm, got ${actualHeightCm}cm (${size.height}pt).`,
    );
  }

  return {
    outputPath,
    pageCount,
    expected: { widthCm: expectedWidthCm, heightCm: expectedHeightCm },
    actualFirstPage: {
      widthPt: size.width,
      heightPt: size.height,
      widthCm: actualWidthCm,
      heightCm: actualHeightCm,
    },
    dimensionsOk: widthOk && heightOk,
    warnings,
  };
}

export function printReport(report: PdfValidationReport): void {
  console.log(`\nOutput: ${report.outputPath}`);
  console.log(`Pages:  ${report.pageCount}`);
  console.log(
    `Expected: ${report.expected.widthCm}cm x ${report.expected.heightCm}cm`,
  );
  console.log(
    `Actual:   ${report.actualFirstPage.widthCm}cm x ${report.actualFirstPage.heightCm}cm ` +
      `(${report.actualFirstPage.widthPt}pt x ${report.actualFirstPage.heightPt}pt)`,
  );
  console.log(
    `Dimensions OK: ${report.dimensionsOk ? "yes" : "NO"}`,
  );

  if (report.warnings.length > 0) {
    console.log(`\nWarnings:`);
    for (const w of report.warnings) {
      console.log(`  - ${w}`);
    }
  }

  const isOnlyCmykWarning =
    report.warnings.length === 1 && report.warnings[0] === CMYK_WARNING;

  if (report.dimensionsOk && isOnlyCmykWarning) {
    console.log(`\nPDF generated successfully.`);
  }

  console.log();
}
